gcp_prod:
  project: strava-exploration-v2
  gcs:
    bucket: strava-api-v3
    folders:
      - activities
      - activity_laps
      - activity_zones
  gbq:
    schema: strava_prod
    tables:
      activities:
        write-disposition: WRITE_APPEND
      activity_laps:
        write-disposition: WRITE_APPEND
      activity_zones:
        write-disposition: WRITE_APPEND
gcp_dev:
  project: strava-exploration-v2
  gcs:
    bucket: strava-api-v3-dev
    folders:
      - activities
      - activity_laps
      - activity_zones
  gbq:
    schema: strava_dev
    tables:
      activities:
        write-disposition: WRITE_TRUNCATE
      activity_laps:
        write-disposition: WRITE_TRUNCATE
      activity_zones:
        write-disposition: WRITE_TRUNCATE
etl:
  activities:
    file_suffix: last_updated
    transform:
      set_values:
        - last_updated
  activity_laps:
    file_suffix: activity_id
    transform:
      set_values:
        - last_updated
  activity_zones:
    file_suffix: activity_id
    transform:
      set_values:
        - last_updated
        - activity_id
      explode_cols:
        - distribution_buckets
tables:
  activities:
    columns:
      - name: resource_state
        type: STRING
      - name: name
        type: STRING
      - name: distance
        type: FLOAT
      - name: moving_time
        type: INTEGER
      - name: elapsed_time
        type: INTEGER
      - name: total_elevation_gain
        type: FLOAT
      - name: type
        type: STRING
      - name: workout_type
        type: STRING
      - name: id
        type: STRING
      - name: start_date
        type: STRING
      - name: start_date_local
        type: STRING
      - name: timezone
        type: STRING
      - name: utc_offset
        type: FLOAT
      - name: location_city
        type: STRING
      - name: location_state
        type: STRING
      - name: location_country
        type: STRING
      - name: achievement_count
        type: INTEGER
      - name: kudos_count
        type: INTEGER
      - name: comment_count
        type: INTEGER
      - name: athlete_count
        type: INTEGER
      - name: photo_count
        type: INTEGER
      - name: trainer
        type: BOOLEAN
      - name: commute
        type: BOOLEAN
      - name: manual
        type: BOOLEAN
      - name: private
        type: BOOLEAN
      - name: visibility
        type: STRING
      - name: flagged
        type: BOOLEAN
      - name: gear_id
        type: STRING
      - name: start_latlng
        type: STRING
      - name: end_latlng
        type: STRING
      - name: average_speed
        type: FLOAT
      - name: max_speed
        type: FLOAT
      - name: average_cadence
        type: FLOAT
      - name: kilojoules
        type: FLOAT
      - name: device_watts
        type: BOOLEAN
      - name: has_heartrate
        type: BOOLEAN
      - name: average_heartrate
        type: FLOAT
      - name: max_heartrate
        type: FLOAT
      - name: heartrate_opt_out
        type: BOOLEAN
      - name: display_hide_heartrate_option
        type: BOOLEAN
      - name: elev_high
        type: FLOAT
      - name: elev_low
        type: FLOAT
      - name: upload_id
        type: STRING
      - name: upload_id_str
        type: STRING
      - name: external_id
        type: STRING
      - name: from_accepted_tag
        type: BOOLEAN
      - name: pr_count
        type: INTEGER
      - name: total_photo_count
        type: INTEGER
      - name: has_kudoed
        type: BOOLEAN
      - name: suffer_score
        type: FLOAT
      - name: athlete_id
        type: STRING
      - name: athlete_resource_state
        type: STRING
      - name: map_id
        type: STRING
      - name: map_summary_polyline
        type: STRING
      - name: map_resource_state
        type: STRING
      - name: last_updated
        type: STRING
      - name: sport_type
        type: STRING
      - name: average_temp
        type: FLOAT
      - name: map
        type: STRING
      - name: average_watts
        type: FLOAT
      - name: weighted_average_watts
        type: FLOAT
      - name: max_watts
        type: FLOAT
  activity_laps:
    columns:
      - name: id
        type: STRING
      - name: resource_state
        type: STRING
      - name: name
        type: STRING
      - name: elapsed_time
        type: INTEGER
      - name: moving_time
        type: INTEGER
      - name: start_date
        type: STRING
      - name: start_date_local
        type: STRING
      - name: distance
        type: FLOAT
      - name: start_index
        type: INTEGER
      - name: end_index
        type: INTEGER
      - name: total_elevation_gain
        type: FLOAT
      - name: average_speed
        type: FLOAT
      - name: max_speed
        type: FLOAT
      - name: device_watts
        type: BOOLEAN
      - name: average_watts
        type: FLOAT
      - name: average_heartrate
        type: FLOAT
      - name: max_heartrate
        type: FLOAT
      - name: lap_index
        type: INTEGER
      - name: split
        type: INTEGER
      - name: activity_id
        type: STRING
      - name: activity_resource_state
        type: STRING
      - name: athlete_id
        type: STRING
      - name: athlete_resource_state
        type: STRING
      - name: pace_zone
        type: INTEGER
      - name: average_cadence
        type: FLOAT
      - name: last_updated
        type: STRING
  activity_zones:
    columns:
      - name: score
        type: FLOAT
      - name: type
        type: STRING
      - name: resource_state
        type: STRING
      - name: sensor_based
        type: BOOLEAN
      - name: points
        type: FLOAT
      - name: custom_zones
        type: BOOLEAN
      - name: activity_id
        type: STRING
      - name: min
        type: FLOAT
      - name: max
        type: FLOAT
      - name: time
        type: INTEGER
      - name: last_updated
        type: STRING
