name: ci-pipeline
on: 
  push:
    branches:
      - github_actions_test
jobs:
  test-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch to runner
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check changes made to python scripts after linting
        run: black *.py --diff

      - name: Apply linting to python scripts
        run: black *.py 

      - name: Apply unit tests to classes
        run: pytest tests/*.py -v --cov --cov-branch --cov-report term-missing
