name: Build, Tag & Push
on: 
  push:
    branches:
      - master

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2

    # - name: Authenticate with GCP
    #   id: auth
    #   uses: google-github-actions/auth@v0
    #   with:
    #     credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # - name: Set-up Google Cloud SDK
    #   uses: google-github-actions/setup-gcloud@v0

    # - name: Configure Docker
    #   run: |
    #     gcloud auth configure-docker

    - name: Get Latest GitHub Release Tag
      uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      with:
        semver_only: true

    - name: Echo New Docker Image Name, with Tag
      shell: bash
      run: |
        echo "Image Name, with Tag: gcr.io/$PROJECT_ID/$CONTAINER_NAME:$CURRENT_VERSION"
      env:
        CURRENT_VERSION: ${{ steps.get-latest-tag.outputs.tag }}
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        CONTAINER_NAME: ${{ secrets.GCP_CONTAINER_NAME }}
      
    # - name: Build, Tag & Push
    #   shell: bash
    #   run: |
    #     docker build . --file Dockerfile --tag gcr.io/strava-exploration-v2/strava-exploration-v2:$CURRENT_VERSION
    #     docker push gcr.io/strava-exploration-v2/strava-exploration-v2:$CURRENT_VERSION
    #   env:
    #     CURRENT_VERSION: ${{ steps.get-latest-tag.outputs.tag }}