name: test
on: 
  push:
    branches:
      - master

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Get Info
      run: |
        gcloud info

    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    - name: Build & Push
      run: |
        docker build -t gcr.io/strava-exploration-v2/strava-exploration-v2:v0.2.1 .
        docker push gcr.io/strava-exploration-v2/strava-exploration-v2:v0.2.1